version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    profiles:
      - local
      - production
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    profiles:
      - local
      - production
    ports:
      - "9092:9092"
    expose:
      - 29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  backend:
    image: backend-module:latest
    container_name: backend
    profiles:
      - production
    build:
      context: ./
      dockerfile: backend.dockerfile
    restart: always
    ports:
      - "8080:8080"
  crawler:
    image: crawler-module:latest
    container_name: crawler
    profiles:
      - production
    build:
      context: ./
      dockerfile: crawler.dockerfile
    restart: always
    ports:
      - "8081:8081"
