/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package at.technikum.commons.schema;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum GameType {
  LEAGUE_OF_LEGENDS, DOTA2  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GameType\",\"namespace\":\"at.technikum.commons.schema\",\"symbols\":[\"LEAGUE_OF_LEGENDS\",\"DOTA2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
